# fly.toml app configuration file generated for catalog-api-rds on 2024-01-28T16:24:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'catalog-api-rds'
primary_region = 'iad'

[build]

[env]
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
